name: "godot-ci export"
on:
  push:
    tags:
      - v*

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: DROITE_1968
  PROJECT_PATH: "."
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME-latest.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/${{ env.EXPORT_NAME }}-latest.exe
      - name: Publish
        run: |
          butler push build/windows/${{ env.EXPORT_NAME }}-latest.exe ${{secrets.ITCHIO_USERNAME}}/${{secrets.ITCHIO_GAME}}:windows --userversion ${{github.ref_name}}
      # - name: Publish
      #   uses: manleydev/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: windows
      #     ITCH_GAME: test-droite1968
      #     ITCH_USER: gigaturbo
      #     VERSION: ${{github.ref_name}}
      #     PACKAGE: build/windows/${{ env.EXPORT_NAME }}-latest.exe

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ./build/linux/$EXPORT_NAME-latest.linux.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux/${{ env.EXPORT_NAME }}-latest.linux.bin
      - name: Publish
        run: |
          butler push ./build/linux/$EXPORT_NAME-latest.linux.bin ${{secrets.ITCHIO_USERNAME}}/${{secrets.ITCHIO_GAME}}:linux --userversion ${{github.ref_name}}
      # - name: Publish
      #   uses: manleydev/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: linux
      #     ITCH_GAME: test-droite1968
      #     ITCH_USER: gigaturbo
      #     VERSION: ${{github.ref_name}}
      #     PACKAGE: build/linux/${{ env.EXPORT_NAME }}-latest.linux.bin


  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ./build/web/index.html
          cd build/web/ && zip ../$EXPORT_NAME-latest.zip ./* && cd $PROJECT_PATH
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/${{ env.EXPORT_NAME }}-latest.zip
      - name: Publish
        run: |
          butler push build/${{ env.EXPORT_NAME }}-latest.zip ${{secrets.ITCHIO_USERNAME}}/${{secrets.ITCHIO_GAME}}:web --userversion ${{github.ref_name}}
      # - name: Publish
      #   uses: manleydev/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: html5
      #     ITCH_GAME: test-droite1968
      #     ITCH_USER: gigaturbo
      #     VERSION: ${{github.ref_name}}
      #     PACKAGE: build/${{ env.EXPORT_NAME }}-latest.zip
        

  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" ./build/mac/${EXPORT_NAME}-latest.macos.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/mac/${{ env.EXPORT_NAME }}-latest.macos.zip
      - name: Publish
        run: |
          butler push build/mac/${{ env.EXPORT_NAME }}-latest.macos.zip ${{secrets.ITCHIO_USERNAME}}/${{secrets.ITCHIO_GAME}}:osx --userversion ${{github.ref_name}}
      # - name: Publish
      #   uses: manleydev/butler-publish-itchio-action@master
      #   env:
      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      #     CHANNEL: mac
      #     ITCH_GAME: test-droite1968
      #     ITCH_USER: gigaturbo
      #     VERSION: ${{github.ref_name}}
      #     PACKAGE: build/mac/${{ env.EXPORT_NAME }}-latest.macos.zip
