name: "godot-ci export"
on:
  push:
    tags:
      - v*

env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: DROITE_1968
  PROJECT_PATH: "."

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME-${{github.ref_name}}.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/${{ env.EXPORT_NAME }}-${{github.ref_name}}.exe
      - name: Publish
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows-latest
          ITCH_GAME: test-droite1968
          ITCH_USER: gigaturbo
          VERSION: ${{github.ref_name}}
          PACKAGE: build/windows/${{ env.EXPORT_NAME }}-${{github.ref_name}}.exe

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ./build/linux/$EXPORT_NAME-${{github.ref_name}}.linux.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/linux/${{ env.EXPORT_NAME }}-${{github.ref_name}}.linux.bin
      - name: Publish
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux-latest
          ITCH_GAME: test-droite1968
          ITCH_USER: gigaturbo
          VERSION: ${{github.ref_name}}
          PACKAGE: build/linux/${{ env.EXPORT_NAME }}-${{github.ref_name}}.linux.bin


  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" ./build/web/index.html
          cd build/web/ && zip ../$EXPORT_NAME-${{github.ref_name}}.zip ./* && cd $PROJECT_PATH
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/${{ env.EXPORT_NAME }}-${{github.ref_name}}.zip
      - name: Publish
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web-latest
          ITCH_GAME: test-droite1968
          ITCH_USER: gigaturbo
          VERSION: ${{github.ref_name}}
          PACKAGE: build/${{ env.EXPORT_NAME }}-${{github.ref_name}}.zip
        

  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "macOS" ./build/mac/$EXPORT_NAME-${{github.ref_name}}.macos.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/mac/${{ env.EXPORT_NAME }}-${{github.ref_name}}.macos.zip
      - name: Publish
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac-latest
          ITCH_GAME: test-droite1968
          ITCH_USER: gigaturbo
          VERSION: ${{github.ref_name}}
          PACKAGE: build/mac/${{ env.EXPORT_NAME }}-${{github.ref_name}}.macos.zip
